missao/urls.py
from django.urls import path

from . import views

app_name = 'missao'

urlpatterns = [
    path('', views.list_missao, name='listamissao'),
    path('<int:pk>/entrar', views.user_missao, name='entrar'),
]

missi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


import noticia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noticia.urls', namespace='noticias')),
    path('cadastro/', include('usuarios.urls', namespace='usuarios')),
    path('missi/', include('missao.urls', namespace='missao')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

noticia/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.post_list, name='post_list')
]

usuarios/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .tokens import user_tokenizer
from django.conf import settings
from . import views
app_name = 'usuarios'

urlpatterns = [
    path('', views.cadastro, name='cadastro'),
    path('login', views.do_login, name='do_login'),
    path('logout', views.do_logout, name='do_logout'),
    path('resetar', include('django.contrib.auth.urls')),
    path('perfil', views.perfil, name='perfil'),
    path('vermissi', views.missi, name='missoesandamento'),
    path('status_missi', views.status, name='status'),
    path('<int:pk>/desistir', views.desistir, name='desistir'),
    path('<int:pk>/finalizando', views.finalizar1, name='final_um'),
    path('<int:pk>/finalizandofim', views.finalizar2, name='final_dois'),
    path('sucesso', views.criarmissi, name='criarmissi'),
    path('patrocine', views.patrocine, name='patrocine'),
    path('sucesso_patrocinio', views.escolhapatrocinio, name='escolha'),
    path('trocarpremio', views.trocarpremio, name='trocarpremio'),
    path('<int:pk>/trocarpremio', views.trocarpremio2, name='trocarfim'),
    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(
          template_name='usuarios/reset_password.html',
          email_template_name='usuarios/reset_password_email.html',
          success_url=settings.LOGIN_URL,
          token_generator=user_tokenizer),
          name='reset_password'
      ),
    path(
        'reset-password-confirmation/<str:uidb64>/<str:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='usuarios/reset_password_update.html',
            post_reset_login=True,
            post_reset_login_backend='django.contrib.auth.backends.ModelBackend',
            token_generator=user_tokenizer,
            success_url=settings.LOGIN_REDIRECT_URL),
        name='password_reset_confirm'
    ),

]

noticia/models.py
from django.db import models

class Noticia(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(max_length=1000)
    data_publi = models.DateTimeField()
    resumo = models.TextField(max_length=200)
    autor = models.CharField(max_length=30)
    foto = models.ImageField(upload_to='noticias', blank=True)

    def __str__(self):
        return "%s noticia: %s" % (self.titulo, self.descricao)

noticia/views.py
from django.shortcuts import render
from django.utils import timezone

from noticia.models import Noticia


def post_list(request):
    noticias = Noticia.objects.filter(data_publi__lte=timezone.now()).order_by('data_publi')
    return render(request, 'noticia/index.html', {'posts': noticias})

templates/noticia/footer.html
<footer style="background-color: black; padding:10px; width: 100%; text-align:center;">
--Missi--


    <div>
    Para ser patrocinador ou para resolver problemas do site, entre em contato pelo e-mail:
    <br>
        meumissi@gmail.com

</div>
    <hr>
<div>
    Design desenvolvido com Mobirise 4 e Bootstrap.

</div>






</footer>

templates/noticia/index.html
<!DOCTYPE html>
{% load static %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.2, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.2, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/animatecss/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">



</head>
<body>
       {% include "noticia/menu.html" %}

  <section class="header10 cid-rFGmOyM5dg mbr-fullscreen mbr-parallax-background" id="header10-1">





    <div class="container">
        <div class="media-container-column mbr-white p-5 align-left col-lg-8 col-md-10">
            <h1 class="mbr-section-title mbr-bold pb-3 mbr-fonts-style display-1"><em>Bem-Vindo</em></h1>

            <p class="mbr-text pb-3 mbr-fonts-style display-5">
               No missi você participa de missões, interage com a comunidade, ganha prêmios e ainda ajuda o meio ambiente.</p>

        </div>
    </div>

    <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
        <a href="#next">
            <i class="mbri-down mbr-iconfont"></i>
        </a>
    </div>
</section>

<section class="engine"><a href="https://mobirise.info/g">how to build a website</a></section><section class="counters5 counters cid-rFGplhZSiZ" id="counters5-2">





    <div class="container pt-4 mt-2">
        <h2 class="mbr-section-title pb-3 align-center mbr-fonts-style display-2">Como funciona</h2>
        <h3 class="mbr-section-subtitle pb-5 align-center mbr-fonts-style display-5">
            Detalhes do Missi</h3>
        <div class="row justify-content-center">
            <div class="cards-block">
                <div class="cards-container">
                    <div class="card px-3 align-left col-12">
                        <div class="panel-item p-4 d-flex">
                            <div class="card-img pr-3">
                                <h3 class="img-text d-flex align-items-center justify-content-center">
                                    1
                                </h3>
                            </div>
                            <div class="card-text">
                                <h4 class="mbr-content-title mbr-bold mbr-fonts-style display-7">Cadastro</h4>
                                <p class="mbr-content-text mbr-fonts-style display-7">
                                    Você faz seu cadastro e o cadastro de suas ideias de missão. É necessário ter detalhes do que planeja fazer e como executar.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card px-3 align-left col-12">
                        <div class="panel-item p-4 d-flex">
                            <div class="card-img pr-3">
                                <h3 class="img-text d-flex align-items-center justify-content-center">
                                    2
                                </h3>
                            </div>
                            <div class="card-text">
                                <h4 class="mbr-content-title mbr-bold mbr-fonts-style display-7">Aprovação</h4>
                                <p class="mbr-content-text mbr-fonts-style display-7">
                                    Suas missões serão enviadas para nossos patrocinadores, que selecionarão as propostas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card px-3 align-left col-12">
                        <div class="panel-item p-4 d-flex">
                            <div class="card-img pr-3">
                                <h3 class="img-text d-flex align-items-center justify-content-center">
                                    3
                                </h3>
                            </div>
                            <div class="card-text">
                                <h4 class="mbr-content-title mbr-bold mbr-fonts-style display-7">Participação</h4>
                                <p class="mbr-content-text mbr-fonts-style display-7">
                                    Quando for validada, sua missão aparecerá para todos participarem.</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section content5 cid-rFGqGMUXGN mbr-parallax-background" id="content5-3">





    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">
                    Recados</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    Ultimas atualizações do Missi.</h3>


            </div>
        </div>
    </div>
</section>

<section class="features3 cid-rFGrswOvmJ" id="features3-4">




    <div class="container">
        <div class="media-container-row">
            {% for post in posts|slice:":3" %}

            <div class="card p-3 col-12 col-md-6 col-lg-4" style="overflow:auto;">
                <div class="card-wrapper">
                    <div class="card-header">{{ post.titulo }}</div>

                    <div class="card-box">

                        <p class="mbr-text mbr-fonts-style display-7">
                           {{ post.resumo }}
                        </p>
                    </div>

                </div>
            </div>

            {% endfor %}





        </div>
    </div>
</section>
{% include "noticia/footer.html" %}

  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/viewportchecker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>


 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
  </body>
</html>

templates/noticia/menu.html
 <nav class="navbar navbar-expand-lg navbar-dark primary-color mbr-text pb-3 mbr-fonts-style display-7" style="background-color: black; ">

                <!-- Navbar brand -->
                <a class="navbar-brand mbr-text pb-3 mbr-fonts-style" href="#">Missi</a>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                  aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                  <!-- Links -->
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'noticias:post_list' %}">Início
                        <span class="sr-only">(current)</span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'missao:listamissao' %}">Ver Missões</a>
                    </li>

                  {% if user.is_authenticated and user.is_staff %}
                       <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink3" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Menu do Patrocinador</a>
                      <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink3">
                        <a class="dropdown-item " href="{% url 'usuarios:patrocine' %}">Patrocinar e meus dados!!</a>
                        <a class="dropdown-item" href="{% url 'usuarios:trocarpremio' %}">Resgatar prêmio</a>
						<a class="dropdown-item" href="{% url 'usuarios:do_logout' %}">Sair</a>
                      </div>
                    </li>

                      {% elif user.is_authenticated %}



                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Perfil</a>
                          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item " href="{% url 'usuarios:perfil' %}">Dados e cadastros</a>
                            <a class="dropdown-item" href="{% url 'usuarios:missoesandamento' %}">Missões em andamento</a>
                            <a class="dropdown-item" href="{% url 'usuarios:status' %}">Missões finalizadas</a>
                            <a class="dropdown-item" href="{% url 'usuarios:do_logout' %}">Sair</a>
                          </div>
                        </li>


				 {% else %}
					  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Entre e participe</a>
                      <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item " href="{% url 'usuarios:do_login' %}">Entrar</a>
                        <a class="dropdown-item" href="{% url 'usuarios:cadastro' %}">Cadastrar</a>

                      </div>
                    </li>

				 {% endif %}

                  </ul>
                  <!-- Links -->


                </div>
                <!-- Collapsible content -->

              </nav>
              <!--/.Navbar-->