missi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


import noticia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noticia.urls', namespace='noticias')),
    path('cadastro/', include('usuarios.urls', namespace='usuarios')),
    path('missi/', include('missao.urls', namespace='missao')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .tokens import user_tokenizer
from django.conf import settings
from . import views
app_name = 'usuarios'

urlpatterns = [
    path('', views.cadastro, name='cadastro'),
    path('login', views.do_login, name='do_login'),
    path('logout', views.do_logout, name='do_logout'),
    path('resetar', include('django.contrib.auth.urls')),
    path('perfil', views.perfil, name='perfil'),
    path('vermissi', views.missi, name='missoesandamento'),
    path('status_missi', views.status, name='status'),
    path('<int:pk>/desistir', views.desistir, name='desistir'),
    path('<int:pk>/finalizando', views.finalizar1, name='final_um'),
    path('<int:pk>/finalizandofim', views.finalizar2, name='final_dois'),
    path('sucesso', views.criarmissi, name='criarmissi'),
    path('patrocine', views.patrocine, name='patrocine'),
    path('sucesso_patrocinio', views.escolhapatrocinio, name='escolha'),
    path('trocarpremio', views.trocarpremio, name='trocarpremio'),
    path('<int:pk>/trocarpremio', views.trocarpremio2, name='trocarfim'),
    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(
          template_name='usuarios/reset_password.html',
          email_template_name='usuarios/reset_password_email.html',
          success_url=settings.LOGIN_URL,
          token_generator=user_tokenizer),
          name='reset_password'
      ),
    path(
        'reset-password-confirmation/<str:uidb64>/<str:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='usuarios/reset_password_update.html',
            post_reset_login=True,
            post_reset_login_backend='django.contrib.auth.backends.ModelBackend',
            token_generator=user_tokenizer,
            success_url=settings.LOGIN_REDIRECT_URL),
        name='password_reset_confirm'
    ),

]

usuarios/models.py
from django.contrib.auth.models import User
from django.db import models


class Perfil(models.Model):
    user = models.OneToOneField(User, default=None, null=True, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='usuarios/media', null=True)
    tipo = models.CharField(max_length=10, null=True)

usuarios/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from missao.form import Addmissao, Patrocinamissao
from missao.models import Missoes, Usuariomissao
from usuarios.form import UserModelForm, PerfilForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from usuarios.models import Perfil


def cadastro(request):
    form = UserModelForm(request.POST or None)
    msg = 'Não pode haver dois usuários com o mesmo e-mail'
    context = {'form': form, 'msg': msg}
    if request.method == 'POST':
        if form.is_valid():
            try:
                usuario_aux = User.objects.get(email=request.POST['email'])
                if usuario_aux:
                    msg = 'Erro! Já existe um usuário com o mesmo e-mail'
                    return render(request, 'usuarios/cadastro.html', {'msg': msg, 'form': form})

            except User.DoesNotExist:
                form.save()
                msg = 'Usuário cadastrado com sucesso'
                return render(request, 'usuarios/cadastro.html', {'msg': msg, 'form': form})
    return render(request, 'usuarios/cadastro.html', context)


def do_login(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('noticias:post_list')
    return render(request, 'usuarios/login.html')


def do_logout(request):
    logout(request)
    return redirect('noticias:post_list')


@login_required()
def perfil(request):
    if request.method == "POST":
        perfil_user, created = Perfil.objects.get_or_create(user=request.user)
        form1 = PerfilForm(request.POST or None, request.FILES or None, instance=perfil_user)
        form = Addmissao(request.POST or None, request.FILES or None)
        user = User.objects.get(id=request.user.id)
        user_name = request.user.first_name
        user_email = request.user.email
        missoes = Missoes.objects.filter(mestre=user)
        if form1.is_valid():
            perfil_user = form1
            perfil_user.user = user
            perfil_user.save()
            return render(request, 'usuarios/cadastrosucess.html',
                          )

    else:
        form = Addmissao()
        form1 = PerfilForm()
        user = User.objects.get(id=request.user.id)
        missoes = Missoes.objects.filter(mestre=user)
        user_name = request.user.first_name
        user_email = request.user.email
        perfil_user = Perfil.objects.filter(user=user)
        if perfil_user:
            perfil_user = Perfil.objects.get(user=user)
            return render(request, 'usuarios/perfil.html',
                          {'user_email': user_email, 'user_name': user_name, 'form': form, 'missoes': missoes,
                           'form1': form1, 'perfil': perfil_user})
        else:
            return render(request, 'usuarios/perfil.html',
                          {'user_email': user_email, 'user_name': user_name, 'form': form, 'missoes': missoes,
                           'form1': form1})


def criarmissi(request):
    if request.method == "POST":

        form = Addmissao(request.POST or None, request.FILES or None)
        user = User.objects.get(id=request.user.id)

        if form.is_valid():
            missao = form.save(commit=False)
            missao.mestre = user
            missao.isValid = False
            missao.pontos = 1
            missao.isTrocado = False
            missao.isTerminado = False
            missao.premio = 'nada ainda'
            missao.cod_premio = 'nada ainda'
            missao.save()
            return render(request, 'usuarios/cadastrosucess.html')


def finalizar1(request, pk):
    missao = Missoes.objects.get(id=pk)
    participantes = Usuariomissao.objects.select_related('id_usuario').filter(id_missao=missao)
    return render(request, 'usuarios/finalizar.html', {'participantes': participantes, 'missao': missao})


@login_required
def finalizar2(request, pk):
    if request.method == 'POST':
        ganhador = request.POST.get('Ganhador')
        user = User.objects.get(id=ganhador)
        missao = Missoes.objects.get(id=pk)
        um = Usuariomissao.objects.get(id_missao=missao, id_usuario=user)
        missao.isTerminada = True
        missao.save()
        um.is_ganhador = True
        um.save()
        return render(request, 'noticia/index.html')


def missi(request):
    user = User.objects.get(id=request.user.id)
    mymissoes = Usuariomissao.objects.select_related('id_missao').filter(id_usuario=user)
    return render(request, 'usuarios/minhasmissoes.html', {'mymissoes': mymissoes})


def desistir(request, pk):
    user = User.objects.get(id=request.user.id)
    missao = Missoes.objects.get(id=pk)
    um = Usuariomissao.objects.get(id_missao=missao, id_usuario=user)
    um.is_desistido = True
    um.save()
    mymissoes = Usuariomissao.objects.select_related('id_missao').filter(id_usuario=user)
    return render(request, 'usuarios/minhasmissoes.html', {'mymissoes': mymissoes})


def status(request):
    user = User.objects.get(id=request.user.id)
    mymissoes = Usuariomissao.objects.select_related('id_missao').filter(id_usuario=user)
    return render(request, 'usuarios/finalizadas.html', {'mymissoes': mymissoes})


def patrocine(request):
    missoes = Missoes.objects.filter(patrocinador='')
    user = User.objects.get(id=request.user.id)
    perfil2 = Perfil.objects.get(user=user)
    missao = Missoes.objects.filter(patrocinador=perfil2.tipo)
    patrocina = Patrocinamissao()
    return render(request, 'usuarios/patrocine.html', {'missoes': missoes, 'form': patrocina, 'quantia': missao})


def escolhapatrocinio(request):
    if request.method == "POST":
        form = Patrocinamissao(request.POST or None)
        if form.is_valid:
            missao = request.POST.get('patrocinar')
            missao1 = Missoes.objects.get(id=missao)
            user = User.objects.get(id=request.user.id)
            perfil1 = Perfil.objects.get(user=user)
            missao1.patrocinador = perfil1.tipo
            missao1.cod_premio = request.POST.get('cod_premio')
            missao1.premio = request.POST.get('premio')
            missao1.save()
            return render(request, 'usuarios/confirmar1.html')


def trocarpremio(request):
    user = User.objects.get(id=request.user.id)
    perfil2 = Perfil.objects.get(user=user)
    missao= Missoes.objects.filter(patrocinador=perfil2.tipo, isTrocado=False)
    return render(request, 'usuarios/trocarpremio.html', {'missoes': missao})


def trocarpremio2(request, pk):
    missao = Missoes.objects.get(id=pk)
    missao.isTrocado = True
    missao.save()
    return render(request, 'usuarios/confirmar2.html')

templates/usuarios/cadastro.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.2, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.2, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/animatecss/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



</head>
<body>
        {% include "noticia/menu.html" %}

  <section class="header10 cid-rFGmOyM5dg mbr-fullscreen " id="header10-1">





    <div class="container col-md-8  mbr-text pb-3 mbr-fonts-style display-7 justify-content-center" style="background-color:white; padding:10px;">
 <h5>{{ msg }}</h5>

<form action="{% url 'usuarios:cadastro' %}"  method="POST" class="form-signin">
                                    {% csrf_token %}
                                   <h2 class="form-signin-headling">Novo usuário</h2>
                                   {{ form|crispy }}

                                   <button class="btn btn-lg btn-primary" type="submit">Cadastre-se</button>
                        </form>
    </div>


</section>

{% include "noticia/footer.html" %}

  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/viewportchecker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>


 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
  </body>
</html>

templates/usuarios/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.2, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.2, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/animatecss/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



</head>
<body>
        {% include "noticia/menu.html" %}

  <section class="header10 cid-rFGmOyM5dg mbr-fullscreen " id="header10-1">





    <div class="container col-md-8  mbr-text pb-3 mbr-fonts-style display-7 justify-content-center" style="background-color:white; padding:10px;">


 <form action="{% url 'usuarios:do_login' %}"  method="POST" class="form-signin">
                                    {% csrf_token %}
                                   <h2 class="form-signin-headling">Entrar</h2>
                                   <label>Nome de usuário</label>
                                   <input type="text" name="username" class="form-control">
                                   <label>Senha</label>
                                   <input type="password" name="password" class="form-control">


                                   <button class="btn btn-lg btn-primary" type="submit">Entre</button>
                                     <div class="control">
                                    <a href="{% url 'usuarios:reset_password' %}">Esqueceu a senha?</a>
                                  </div>
                               </form>
    </div>


</section>

{% include "noticia/footer.html" %}
  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/viewportchecker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>


 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
  </body>
</html>

templates/usuarios/perfil.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.2, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.2, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/animatecss/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">



</head>
<body>
        {% include "noticia/menu.html" %}

  <section class="carousel slide testimonials-slider cid-rFGv4bOju9" data-interval="false" id="testimonials-slider1-a">



    <div class="mbr-overlay" style="opacity: 0.6; background-color: rgb(165, 249, 167);">
    </div>

    <div class="container text-center">
        <h2 class="pb-5 mbr-fonts-style display-2">Perfil!</h2>

        <div class="user col-md-12">
                <div class="user_image">
                    {% if perfil.foto %}
                    <img src="{{ MEDIA_URL }}{{perfil.foto.url}}">
                    {% else %}
                    <h3 style="padding:20px;">Adicione uma foto</h3>
                    {% endif %}
                </div>
                <div class="user_text pb-3">
                </div>
                <div class="user_name mbr-bold pb-2 mbr-fonts-style display-7">
                   {{ user_name }}
                </div>
                <div class="user_desk mbr-light mbr-fonts-style display-7">
                    {{ user_email }}
                </div>
            <button type="button" class="btn  btn-lg  btn-primary" data-toggle="modal" data-target=".bd-example-modal-sm">Editar foto</button>

                <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                       <form method="POST" enctype="multipart/form-data" class="post-form">{% csrf_token %}
                    {{ form1|crispy }}
                    <button type="submit" class="save btn btn-default btn-outline-secondary">Save</button>
                </form>

                    </div>
                  </div>
                </div>

            </div>
    </div>
</section>

<section class="engine"><a href="https://mobirise.info/b">create a site for free</a></section><section class="mbr-section article content9 cid-rFGwmck9vz" id="content9-b">



    <div class="container">
        <div class="inner-container" style="width: 100%;">
            <hr class="line" style="width: 25%;">
            <div class="section-text align-center mbr-fonts-style display-5">"Vamos olhar para a Terra e seu planetas irmãos como coexistindo com a gente, em vez de feitos para nós."
<div>Mary Daly</div></div>
            <hr class="line" style="width: 25%;">
        </div>
        </div>
</section>

<section class="mbr-section form1 cid-rFGyzLYEjF" id="form1-c">




    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">
                    Cadastre uma missão</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light pb-3 mbr-fonts-style display-5">
                    Lembre-se que ela precisa ser aprovada para poder ter participantes.</h3>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8" >
                 <form method="POST"  enctype="multipart/form-data" action="{% url 'usuarios:criarmissi' %}" class="post-form">{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="save btn btn-default btn-outline-secondary">Save</button>
                </form>

            </div>
        </div>
    </div>
</section>

<section class="mbr-section content5 cid-rFGz9d92qD mbr-parallax-background" id="content5-e">





    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">
                    Status</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    Acompanhe se sua missão foi aprovada, entre outros dados...</h3>


            </div>
        </div>
    </div>
</section>

<section class="features3 cid-rFGzabOK9A" id="features3-f">




    <div class="container" style="background-color:white; overflow:auto;">
        <div class="cards-container ">
            {%  for missao in missoes %}
            <div class="card  col-md-3" style="float:left; height:250px; margin:5px; background-color:#f9f295; overflow:auto;">
                <div class="card-wrapper">
                    <div class="card-header">
                         {{ missao.titulo }}
                    </div>

                    <div class="card-box">
                        <p class="mbr-text mbr-fonts-style display-7">
                           {{ missao.descricao|truncatewords:11 }}
                        </p>
                    </div>
                    <div class="mbr-section-btn text-center">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".{{ missao.titulo|slugify }}">Veja + dados</button>

                            <div class="modal fade bd-example-modal-lg {{ missao.titulo|slugify }}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                              <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header" style="background-color:#f9f295; ">
                                    <h5 class="modal-title" id="exampleModalLabel">Status de: {{ missao.titulo }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body container-fluid pb-3 mbr-fonts-style ">
                                      <div class="row">
                                          <div class="col-md-5">
                                              <h5>Descrição:<br> {{ missao.descricao }}
                                      <br><br><br></h5>

                                          </div>
                                          <div class="col-md-5">
                                               <h5>Utilidade:<br>{{ missao.utilidade }}<br><br><br></h5>
                                      <br>
                                      <br>
                                          </div>
                                          <div class="col-md-12" style="text-align:left;">
                                              {%  if missao.arquivo %}
                                      <a href="{{ MEDIA_URL }}{{missao.arquivo.url}}" target="_blank" class="text-secondary"><h5>Arquivo da missão</h5></a>
                                      {%  endif %}
                                          </div>


                                      </div>



                                      <hr>


                                       {% if missao.isValid %}
                                      {% if missao.isTerminada %}
                                      <h5>Essa missão já foi concluida.</h5>

                                      {%  else %}
                                       {%  if missao.patrocinador %}
                                          <h5>A sua missão é patrocinada por {{ missao.patrocinador }} com o prêmio {{ missao.premio }}</h5>
                                          <a href="{% url 'usuarios:final_um' pk=missao.id  %}" class="btn btn-default" style="width:160px;">Finalizar</a>


                                       {% else %}
                                        <div style=" margin-bottom:20px;" class="col-md-12" >
                                           <h5>Parabéns, sua missão já foi validada pelo sistema! </h5>
                                            <br>

                                          <h3>Aguarde um patrocinador para começar</h3>

                                        </div>
                                      {% endif %}
                                      {% endif %}


                                        {% else %}

                                        <div style=" margin-bottom:20px;" class="col-md-12">
                                            <h5>Sua missão ainda não foi validada, aguarde.</h5>

                                        </div>

                                        {% endif %}



                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn" data-dismiss="modal">Fechar</button>
                                    <button type="button" class="btn btn-primary">Enviar</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                    </div>
                </div>
            </div>
            {% endfor %}
                <div style="clear:both;"></div>



        </div>
    </div>
</section>
{% include "noticia/footer.html" %}

  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/viewportchecker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>


 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
  </body>
</html>

templates/usuarios/reset_password_email.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django Survey Password Reset</title>
</head>
<body>
  <h1>Missi: Resetar senha.</h1>
  <p>Por favor, clique no link abaixo para modificar sua senha.</p>
  <p><a href="{{ protocol}}://{{ domain }}{% url 'usuarios:password_reset_confirm' uidb64=uid token=token %}">Mudar senha</a></p>
</body>
</html>